spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
  

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      
logging:
  level:
    root: INFO
    edu.czjtu.big_event_demo.interceptors: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"